### ISSUE TITLE
set extension as `.comapeocat`

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-settings-builder#68]

**Comment by EvanHahn** [comment]
I'm new to this repo, but I don't understand why we need to do anything here. It seems like the `--output=<filename>` flag doesn't dictate a file extension.

Is this something we can solve with documentation, or just not do at all?

**Comment by tomasciccola** [comment]
Yep, you're right. the output extension itself is usually 'enforced' on every config repo separately, which is kind of a drag. 
By default the config builder just outputs the raw file to stdout. 

We can:
* Be less unixi and always output to a file with `.comapeocat` extension (grabbing the name of the config from the metadata itself)
* Be a _little_ less unixi. If you pass `--output` then the file extension is enforced
* Do nothing?


Wonder what @gmaclennan thinks...

**Comment by EvanHahn** [comment]
I genuinely like the "do nothing" option the best...

**Comment by tomasciccola** [comment]
Yeah, I _kinda_ think that for now it makes sense. Its kind of a brittle approach that can be addressed by the UI of the config builder. Because for now, what we need to do is to update the `npm build` script on any config repo so that it has the correct extension.
In any case, as things are now, this can't be addressed here, so closing the issue
